### ISSUE TITLE
Installer failing to build

### ISSUE THREAD

**Issue by danscodelab** [flybywiresim/installer#280]
### Installer Version

v1.2.0

### Issue with `webpack-asset-relocater-loader`

When trying to build the installer with `npm start / yarn start` the installer fails to build

**Error Message:**

`index.esm.js:6185 Uncaught Error: Module build failed (from ./node_modules/@marshallofsound/webpack-asset-relocator-loader/dist/index.js):
SyntaxError: Unexpected token (191:27)
    at Object.module.exports.pp$4.raise (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:20834:13)
    at Object.module.exports.pp.unexpected (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:18680:8)
    at Object.module.exports.pp$3.parseExprAtom (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:20282:10)
    at Object.parseExprAtom (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:4551:117)
    at Object.parseExprAtom (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:42293:75)
    at Object.parseExprAtom (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:35894:26)
    at Object.parseExprAtom (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:15975:26)
    at Object.parseExprAtom (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:380:26)
    at Object.module.exports.pp$3.parseExprSubscripts (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:20116:19)
    at Object.module.exports.pp$3.parseMaybeUnary (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:20093:17)
    at Object.parseMaybeUnary (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:35875:29)
    at Object.parseMaybeUnary (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:15955:29)
    at Object.parseMaybeUnary (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:368:29)
    at Object.module.exports.pp$3.parseExprOps (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:20035:19)
    at Object.module.exports.pp$3.parseMaybeConditional (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:20018:19)
    at Object.module.exports.pp$3.parseMaybeAssign (C:\Users\danie\Downloads\installer-master\installer-master\node_modules\@marshallofsound\webpack-asset-relocator-loader\dist\index.js:19993:19)
    at Object../node_modules/@flybywiresim/react-components/build/index.esm.js (http://localhost:3000/main_window/index.js:56217:7)
    at __webpack_require__ (http://localhost:3000/main_window/index.js:790:30)
    at fn (http://localhost:3000/main_window/index.js:101:20)
    at Object../src/renderer/components/GeneralSettings/index.tsx (http://localhost:3000/main_window/index.js:327335:28)
    at __webpack_require__ (http://localhost:3000/main_window/index.js:790:30)
    at fn (http://localhost:3000/main_window/index.js:101:20)
    at Object../src/renderer/components/SettingsSection/index.tsx (http://localhost:3000/main_window/index.js:327759:43)
    at __webpack_require__ (http://localhost:3000/main_window/index.js:790:30)
    at fn (http://localhost:3000/main_window/index.js:101:20)
    at Object.<anonymous> (http://localhost:3000/main_window/index.js:326759:43)`

Also there seems to be an issue with `Electron-Forge` when trying to build the Installer:

`An unhandled rejection has occurred inside Forge: Use delete() to clear values`

### Expected behavior

Installer builds successfully

### Steps to reproduce

1. Clone the Repository 
2. Install the dependencies with `Npm install / Yarn`
3. Run the Installer with `Npm Start / Yarn start`

### Discord Username (optional)

dan #0001

**Comment by FoxtrotSierra6829** [comment]
sorry, no support for this issue until #205 is merged

**Comment by danscodelab** [comment]
> sorry, no support for this issue until #205 is merged

rgr

**Comment by FoxtrotSierra6829** [comment]
you can try to rebuild with the current master version

**Comment by danisbored** [comment]
> you can try to rebuild with the current master version

Worked - issue is fixed
